### ISSUE TITLE
Server is crashing, when HighLevelChangesList is applied

### ISSUE THREAD

**Issue by micstra** [gentics/mesh#1152]
## Gentics Mesh Version, operating system, or hardware.
- v1.7.2

## Operating System
- Docker-Container, Docker for Windows

## Problem
When migrating from a version < 1.7,2 to a version >= 1,7,2 the HighLevelChangesList cannot be applied properly. This results in a server shutdown immediately after startup.

## Reproducer
1. Create a new docker-container(with version 1.7.1) with a new/empty volume for the grapdhb: 
`docker run -v mesh-storage:/graphdb -p 8080:8080 gentics/mesh:1.7.1`
2. Stop the running docker-container 
3. Create a new docker-container(with version 1.7.2) and mount the existing volume for the graphdb:
`docker run -v mesh-storage:/graphdb -p 8080:8080 gentics/mesh:1.7.2`

During startup of the second container the high level change log is executed, which cause the container to fail.

## Expected behaviour and actual behaviour
Expected: The migration is applied properly and the server starts accepting requests. 

Actual: 

Following stacktrace is printed during startup and the server shuts down: 

```
INFO: Storage 'plocal:/graphdb/storage' is opened under OrientDB distribution : 3.0.28 - Veloce (build 7f2fc09560546cde8f7cfacd91423de88b192678, branch UNKNOWN)
15:16:31.366 [] INFO  [main] [c.g.m.c.BootstrapInitializer] - Invoking database changelog check...
15:16:31.491 [] INFO  [main] [c.g.m.c.d.i.DatabaseHelper] - Creating database indices. This may take a few seconds...
15:16:32.281 [] INFO  [main] [c.g.m.c.h.c.PrepareBucketableElements] - Applying change: PrepareBucketableElements
15:16:32.289 [] INFO  [main] [c.g.m.c.h.c.PrepareBucketableElements] - Migrated {0} of type {UserImpl}
15:16:32.292 [] ERROR [main] [c.g.m.c.h.HighLevelChangelogSystemImpl] - Error while executing change {PrepareBucketableElements}/{BEB88BA9CF494CA59FFF3329F4DE1764}
java.lang.NullPointerException: null
        at com.gentics.mesh.changelog.highlevel.change.PrepareBucketableElements.migrate(PrepareBucketableElements.java:75)
        at com.gentics.mesh.changelog.highlevel.change.PrepareBucketableElements.apply(PrepareBucketableElements.java:56)
        at com.gentics.mesh.changelog.highlevel.HighLevelChangelogSystemImpl.lambda$apply$0(HighLevelChangelogSystemImpl.java:46)
        at com.gentics.mesh.core.db.TxFactory.lambda$tx$2(TxFactory.java:83)
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:462)
        at com.gentics.mesh.core.db.TxFactory.tx(TxFactory.java:82)
        at com.gentics.mesh.changelog.highlevel.HighLevelChangelogSystemImpl.lambda$apply$2(HighLevelChangelogSystemImpl.java:42)
        at com.gentics.mesh.core.db.TxFactory.lambda$tx$2(TxFactory.java:83)
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:462)
        at com.gentics.mesh.core.db.TxFactory.tx(TxFactory.java:82)
        at com.gentics.mesh.changelog.highlevel.HighLevelChangelogSystemImpl.apply(HighLevelChangelogSystemImpl.java:38)
        at com.gentics.mesh.cli.BootstrapInitializerImpl.invokeChangelog(BootstrapInitializerImpl.java:748)
        at com.gentics.mesh.cli.BootstrapInitializerImpl.initLocalData(BootstrapInitializerImpl.java:284)
        at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:364)
        at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:146)
        at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:107)
        at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:44)
15:16:32.293 [] ERROR [main] [c.g.m.cli.MeshImpl] - Error while starting mesh
java.lang.RuntimeException: Error while executing high level changelog.
        at com.gentics.mesh.changelog.highlevel.HighLevelChangelogSystemImpl.lambda$apply$2(HighLevelChangelogSystemImpl.java:60)
        at com.gentics.mesh.core.db.TxFactory.lambda$tx$2(TxFactory.java:83)
        at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:462)
        at com.gentics.mesh.core.db.TxFactory.tx(TxFactory.java:82)
        at com.gentics.mesh.changelog.highlevel.HighLevelChangelogSystemImpl.apply(HighLevelChangelogSystemImpl.java:38)
        at com.gentics.mesh.cli.BootstrapInitializerImpl.invokeChangelog(BootstrapInitializerImpl.java:748)
        at com.gentics.mesh.cli.BootstrapInitializerImpl.initLocalData(BootstrapInitializerImpl.java:284)
        at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:364)
        at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:146)
        at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:107)
        at com.gentics.mesh.server.ServerRunner.main(ServerRunner.java:44)
15:16:32.294 [] INFO  [main] [c.g.m.cli.MeshImpl] - Mesh shutting down...
15:16:32.326 [] INFO  [main] [c.g.m.cli.MeshImpl] - Stopping search provider
15:16:32.331 [] INFO  [main] [c.g.m.cli.MeshImpl] - Stopping Vert.x
15:16:34.381 [] INFO  [main] [c.g.m.g.c.OrientDBClusterManager] - Stopping cluster manager
15:16:34.381 [] INFO  [main] [c.g.m.cli.MeshImpl] - Shutdown completed...
15:16:35.378 [] INFO  [Thread-0] [c.g.m.cli.MeshImpl] - Instance is already shut down...
Oct 29, 2020 3:16:35 PM com.orientechnologies.common.log.OLogManager log
INFO: Orient Engine is shutting down...  
```

**Comment by Jotschi** [comment]
It seems the needed transaction is not active and thus a NPE occurred.

**Comment by Jotschi** [comment]
Fixed within 1.7.5

**Comment by suihanhbr** [comment]
@Jotschi It still crashed in 1.7.1/1.7.2/1.7.3/1.7.4/1.7.5/1.7.6.

There is my log:
```
07:38:56.814 [] INFO  [main] [c.g.m.OptionsLoader] - Configuration file {mesh.yml} was not found within classpath.
07:38:56.818 [] INFO  [main] [c.g.m.OptionsLoader] - Loading configuration file {config/mesh.yml}.
07:38:57.341 [] INFO  [main] [c.g.m.cli.MeshImpl] - ###############################################################
07:38:57.360 [] INFO  [main] [c.g.m.cli.MeshImpl] - # Mesh Version 1.7.4 2020-10-22T17:01:52Z                     #
07:38:57.361 [] INFO  [main] [c.g.m.cli.MeshImpl] - # Gentics Software                                            #
07:38:57.361 [] INFO  [main] [c.g.m.cli.MeshImpl] - #-------------------------------------------------------------#
07:38:57.371 [] INFO  [main] [c.g.m.cli.MeshImpl] - # Vert.x Version: 3.8.5                                       #
07:38:57.372 [] INFO  [main] [c.g.m.cli.MeshImpl] - # Mesh Node Name: Galactical Monferno                         #
07:38:57.372 [] INFO  [main] [c.g.m.cli.MeshImpl] - ###############################################################
07:38:58.113 [] INFO  [main] [c.g.m.p.m.MeshPluginManagerImpl] - PF4J version 0.0.0 in 'deployment' mode
07:38:58.202 [] WARN  [main] [c.g.m.c.BootstrapInitializer] - Keyfile {config/public-keys.json} not found. Not loading keys..
2月 11, 2021 7:38:58 上午 com.orientechnologies.common.log.OLogManager log
信息: Default limit of open files (512) will be used.
07:38:58.873 [] INFO  [main] [c.g.m.c.BootstrapInitializer] - Enabling Vert.x metrics
07:38:58.875 [] INFO  [main] [c.g.m.c.BootstrapInitializer] - Creating non-clustered Vert.x instance
07:38:59.290 [] WARN  [main] [c.g.m.c.BootstrapInitializer] - Current environment does not support native transports
07:38:59.324 [] INFO  [main] [c.g.m.s.ElasticsearchProcessManager] - Starting watchdog for Elasticsearch process
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Warning: Nashorn engine is planned to be removed from a future JDK release
2月 11, 2021 7:39:00 上午 com.orientechnologies.common.log.OLogManager log
信息: 17179869184 B/16384 MB/16 GB of physical memory were detected on machine
2月 11, 2021 7:39:00 上午 com.orientechnologies.common.log.OLogManager log
信息: Detected memory limit for current process is 17179869184 B/16384 MB/16 GB
2月 11, 2021 7:39:00 上午 com.orientechnologies.common.log.OLogManager log
信息: JVM can use maximum 4096MB of heap memory
2月 11, 2021 7:39:00 上午 com.orientechnologies.common.log.OLogManager log
信息: Because OrientDB is running outside a container 2g of memory will be left unallocated according to the setting 'memory.leftToOS' not taking into account heap memory
2月 11, 2021 7:39:00 上午 com.orientechnologies.common.log.OLogManager log
信息: OrientDB auto-config DISKCACHE=10,240MB (heap=4,096MB os=16,384MB)
2月 11, 2021 7:39:00 上午 com.orientechnologies.common.log.OLogManager log
信息: System is started under an effective user : `huangboru`
2月 11, 2021 7:39:00 上午 com.orientechnologies.common.log.OLogManager log
信息: Allocation of 155648 pages.
2月 11, 2021 7:39:01 上午 com.orientechnologies.common.log.OLogManager log
信息: WAL maximum segment size is set to 23,785 MB
2月 11, 2021 7:39:01 上午 com.orientechnologies.common.log.OLogManager log
信息: Page size for WAL located in /Users/huangboru/myfile/SeverBackUp/CMS/2021-02-10-225641/data/graphdb/storage is set to 4096 bytes.
2月 11, 2021 7:39:02 上午 com.orientechnologies.common.log.OLogManager log
信息: DWL:storage: block size = 4096 bytes, maximum segment size = 23785 MB
2月 11, 2021 7:39:02 上午 com.orientechnologies.common.log.OLogManager log
严重: File with startup metadata is broken and can not be used, creation of new one
2月 11, 2021 7:39:02 上午 com.orientechnologies.common.log.OLogManager log
警告: Storage 'storage' was not closed properly. Will try to recover from write ahead log
2月 11, 2021 7:39:02 上午 com.orientechnologies.common.log.OLogManager log
信息: Looking for last checkpoint...
2月 11, 2021 7:39:02 上午 com.orientechnologies.common.log.OLogManager log
严重: WAL page 0 of segment storage.2091.wal is broken, read of records will be stopped
2月 11, 2021 7:39:02 上午 com.orientechnologies.common.log.OLogManager log
信息: Checkpoints are absent, the restore will start from the beginning.
2月 11, 2021 7:39:02 上午 com.orientechnologies.common.log.OLogManager log
信息: Data restore procedure is started.
2月 11, 2021 7:39:02 上午 com.orientechnologies.common.log.OLogManager log
严重: WAL page 0 of segment storage.2091.wal is broken, read of records will be stopped
2月 11, 2021 7:39:02 上午 com.orientechnologies.common.log.OLogManager log
信息: Storage data recover was completed
[2021-02-11T07:39:02,899][INFO ][o.e.n.Node               ] [] initializing ...
[2021-02-11T07:39:03,215][INFO ][o.e.e.NodeEnvironment    ] [vA9wm7h] using [1] data paths, mounts [[/System/Volumes/Data (/dev/disk3s1)]], net usable_space [463.8gb], net total_space [931.3gb], types [apfs]
[2021-02-11T07:39:03,216][INFO ][o.e.e.NodeEnvironment    ] [vA9wm7h] heap size [990.7mb], compressed ordinary object pointers [true]
[2021-02-11T07:39:03,222][INFO ][o.e.n.Node               ] node name [vA9wm7h] derived from node ID [vA9wm7hFTqmg-f-7DSjGCA]; set [node.name] to override
[2021-02-11T07:39:03,223][INFO ][o.e.n.Node               ] version[6.1.2], pid[5559], build[5b1fea5/2018-01-10T02:35:59.208Z], OS[Mac OS X/10.15.7/x86_64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/11.0.7/11.0.7+10]
[2021-02-11T07:39:03,223][INFO ][o.e.n.Node               ] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/Users/huangboru/myfile/SeverBackUp/CMS/2021-02-10-225641/./elasticsearch, -Des.path.conf=/Users/huangboru/myfile/SeverBackUp/CMS/2021-02-10-225641/./elasticsearch/config]
2月 11, 2021 7:39:04 上午 com.orientechnologies.common.log.OLogManager log
严重: Exception `29F38091` in storage `plocal:/Users/huangboru/myfile/SeverBackUp/CMS/2021-02-10-225641/data/graphdb/storage`: 3.1.4 - Veloce (build 0d47e1cd37cb69c185fb4959e925863e8ca3abcf, branch UNKNOWN)
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage storage
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:195)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:438)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:483)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:928)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:437)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:304)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:259)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:178)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:82)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:125)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$1.getGraph(OrientGraphFactory.java:92)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:242)
	at com.gentics.mesh.graphdb.tx.impl.OrientLocalStorageImpl.rawTx(OrientLocalStorageImpl.java:55)
	at com.syncleus.ferma.ext.orientdb3.OrientDBTx.<init>(OrientDBTx.java:57)
	at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:419)
	at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:465)
	at com.gentics.mesh.graphdb.OrientDBDatabase.isEmptyDatabase(OrientDBDatabase.java:707)
	at com.gentics.mesh.cli.BootstrapInitializerImpl.isEmptyInstallation(BootstrapInitializerImpl.java:763)
	at com.gentics.mesh.cli.BootstrapInitializerImpl.initLocalData(BootstrapInitializerImpl.java:258)
	at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:397)
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:145)
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:107)
	at com.gentics.mesh.demo.DemoRunner.main(DemoRunner.java:65)
Caused by: java.lang.IllegalArgumentException: Unsupported version of index : 1
	at com.orientechnologies.orient.core.index.engine.v1.OCellBTreeMultiValueIndexEngine.<init>(OCellBTreeMultiValueIndexEngine.java:55)
	at com.orientechnologies.orient.core.index.ODefaultIndexFactory.createIndexEngine(ODefaultIndexFactory.java:236)
	at com.orientechnologies.orient.core.index.OIndexes.createIndexEngine(OIndexes.java:202)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openIndexes(OAbstractPaginatedStorage.java:577)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:462)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:189)
	... 22 more

07:39:04.354 [] ERROR [main] [c.g.m.d.DemoRunner] - Error while starting mesh. Invoking shutdown.
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'storage'
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:503)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:928)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:437)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:304)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:259)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:178)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:82)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:125)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$1.getGraph(OrientGraphFactory.java:92)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:242)
	at com.gentics.mesh.graphdb.tx.impl.OrientLocalStorageImpl.rawTx(OrientLocalStorageImpl.java:55)
	at com.syncleus.ferma.ext.orientdb3.OrientDBTx.<init>(OrientDBTx.java:57)
	at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:419)
	at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:465)
	at com.gentics.mesh.graphdb.OrientDBDatabase.isEmptyDatabase(OrientDBDatabase.java:707)
	at com.gentics.mesh.cli.BootstrapInitializerImpl.isEmptyInstallation(BootstrapInitializerImpl.java:763)
	at com.gentics.mesh.cli.BootstrapInitializerImpl.initLocalData(BootstrapInitializerImpl.java:258)
	at com.gentics.mesh.cli.BootstrapInitializerImpl.init(BootstrapInitializerImpl.java:397)
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:145)
	at com.gentics.mesh.cli.MeshImpl.run(MeshImpl.java:107)
	at com.gentics.mesh.demo.DemoRunner.main(DemoRunner.java:65)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage storage
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:195)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:438)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:483)
	... 20 common frames omitted
Caused by: java.lang.IllegalArgumentException: Unsupported version of index : 1
	at com.orientechnologies.orient.core.index.engine.v1.OCellBTreeMultiValueIndexEngine.<init>(OCellBTreeMultiValueIndexEngine.java:55)
	at com.orientechnologies.orient.core.index.ODefaultIndexFactory.createIndexEngine(ODefaultIndexFactory.java:236)
	at com.orientechnologies.orient.core.index.OIndexes.createIndexEngine(OIndexes.java:202)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openIndexes(OAbstractPaginatedStorage.java:577)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:462)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:189)
	... 22 common frames omitted
07:39:04.389 [] INFO  [Thread-0] [c.g.m.cli.MeshImpl] - Mesh shutting down...
07:39:04.413 [] INFO  [Thread-0] [c.g.m.cli.MeshImpl] - Setting shutdown status
07:39:04.413 [] INFO  [Thread-0] [c.g.m.cli.MeshImpl] - Undeploying plugins
07:39:04.478 [] INFO  [Thread-0] [c.g.m.cli.MeshImpl] - Stopping search provider
07:39:04.478 [] INFO  [Thread-0] [c.g.m.s.i.ElasticSearchProvider] - Closing Elasticsearch REST client.
07:39:04.479 [] INFO  [Thread-0] [c.g.m.s.i.ElasticSearchProvider] - Stopping Elasticsearch server.
07:39:04.484 [] INFO  [Thread-0] [c.g.m.cli.MeshImpl] - Stopping Vert.x
07:39:04.514 [] INFO  [Thread-0] [c.g.m.cli.MeshImpl] - Stopping and closing database provider
07:39:04.516 [] INFO  [Thread-0] [c.g.m.g.c.OrientDBClusterManager] - Stopping cluster manager
07:39:04.516 [] INFO  [Thread-0] [c.g.m.cli.MeshImpl] - Shutting database provider down
07:39:05.145 [] INFO  [Thread-0] [c.g.m.cli.MeshImpl] - Clearing references
07:39:05.146 [] INFO  [Thread-0] [c.g.m.cli.MeshImpl] - Shutdown completed...
07:39:05.417 [] INFO  [Thread-5] [c.g.m.s.ElasticsearchProcessManager] - Terminating Elasticsearch process..
```
